### ISSUE TITLE
On import contact(s) invalid public key is added to contacts.

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#374]
Steps to reproduce
1) start 2 clients and create identities in each of them.
2) send one of its contact to other client.
3) In the other contact do import contacts

On import contact(s) invalid public key is added to contacts.

Tested in Debain and is always reproducible.

**Comment by PaulEU** [comment]
I fixed at rev: 46f8cffb39703ad01228657a3f38a67716a0a605
Import contact(s) have been ok, but public key wasn't displayed when keyhotee ID wasn't registered in blockchain.

**Comment by yuvarajgogoi** [comment]
Issue still reproducible screenshot attached: ![invalid_public_key_import](https://cloud.githubusercontent.com/assets/5823578/3026119/3cc414b6-e00f-11e3-8a04-488510a57d00.png)
